import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '../components/sidebar/Sidebar';
import Navbar from '../components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="h-full">
			<body className={`${inter.className} h-full flex flex-col overflow-hidden`}>
				<Navbar />
				<div className="flex flex-1 overflow-hidden">
					<Sidebar />
					<main className="flex-grow p-4 overflow-y-auto">{children}</main>
				</div>
			</body>
		</html>
	);
}
